from PyQt5 import QtCore, QtGui, QtWidgets
from ui_Widgets import uni_Widget


class ui_UrlPanel(QtWidgets.QWidget):
    def __init__(self):
        super(ui_UrlPanel, self).__init__()
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.UrlTableTips = uni_Widget.ICTFELabel(self)
        self.UrlTableTips.setObjectName("UrlTableTips")
        self.horizontalLayout.addWidget(self.UrlTableTips)
        self.UrlTableBox = uni_Widget.ICTFELineBox(self)
        self.UrlTableBox.setObjectName("UrlTableBox")
        self.horizontalLayout.addWidget(self.UrlTableBox)
        self.AllCheckBox = uni_Widget.ICTFECheckBox(self)
        self.AllCheckBox.setMinimumSize(QtCore.QSize(120, 45))
        self.AllCheckBox.setMaximumSize(QtCore.QSize(120, 45))
        self.AllCheckBox.setObjectName("AllCheckBox")
        self.horizontalLayout.addWidget(self.AllCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.UrlEncodeButton = uni_Widget.ICTFEButton(self)
        self.UrlEncodeButton.setMinimumSize(QtCore.QSize(120, 45))
        self.UrlEncodeButton.setMaximumSize(QtCore.QSize(120, 45))
        self.UrlEncodeButton.setObjectName("UrlEncodeButton")
        self.horizontalLayout.addWidget(self.UrlEncodeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.UrlTextBox = uni_Widget.ICTFETextBox(self)
        self.UrlTextBox.setObjectName("UrlTextBox")
        self.verticalLayout.addWidget(self.UrlTextBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.UrlDecodeButton = uni_Widget.ICTFEButton(self)
        self.UrlDecodeButton.setMinimumSize(QtCore.QSize(120, 45))
        self.UrlDecodeButton.setMaximumSize(QtCore.QSize(120, 45))
        self.UrlDecodeButton.setObjectName("UrlDecodeButton")
        self.horizontalLayout_2.addWidget(self.UrlDecodeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.UrlCipherBox = uni_Widget.ICTFETextBox(self)
        self.UrlCipherBox.setObjectName("UrlCipherBox")
        self.verticalLayout_2.addWidget(self.UrlCipherBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.UrlTableTips.setText(_translate("self", "编码表:"))
        self.AllCheckBox.setText(_translate("self", "All"))
        self.UrlEncodeButton.setText(_translate("self", "编码"))
        self.UrlDecodeButton.setText(_translate("self", "解码"))
