from PyQt5 import QtCore, QtWidgets
from ui_Widgets import uni_Widget


class ui_HashPanel(QtWidgets.QWidget):
    def __init__(self):
        super(ui_HashPanel, self).__init__()

        # input text file button
        self.HashTextInputPath = ''
        self.HashTextInputFlag = False
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.HashTextInputButton = uni_Widget.ICTFEButton(self)
        self.HashTextInputButton.setMinimumSize(QtCore.QSize(120, 45))
        self.HashTextInputButton.setMaximumSize(QtCore.QSize(120, 45))
        self.HashTextInputButton.setObjectName("HashTextInputButton")
        self.horizontalLayout.addWidget(self.HashTextInputButton)
        self.HashEncodingTips = uni_Widget.ICTFELabel(self)
        self.HashEncodingTips.setObjectName("HashEncodingTips")
        self.horizontalLayout.addWidget(self.HashEncodingTips)
        self.HashEncodingBox = uni_Widget.ICTFELineBox(self)
        self.HashEncodingBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.HashEncodingBox.setObjectName("HashEncodingBox")
        self.horizontalLayout.addWidget(self.HashEncodingBox)
        self.HashSaltTips = uni_Widget.ICTFELabel(self)
        self.HashSaltTips.setObjectName("HashSaltTips")
        self.horizontalLayout.addWidget(self.HashSaltTips)
        self.HashSaltBox = uni_Widget.ICTFELineBox(self)
        self.HashSaltBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.HashSaltBox.setObjectName("HashSaltBox")
        self.horizontalLayout.addWidget(self.HashSaltBox)
        self.HashEvalCheckBox = uni_Widget.ICTFECheckBox(self)
        self.HashEvalCheckBox.setMinimumSize(QtCore.QSize(60, 45))
        self.HashEvalCheckBox.setMaximumSize(QtCore.QSize(60, 45))
        self.HashEvalCheckBox.setObjectName("HashEvalCheckBox")
        self.horizontalLayout.addWidget(self.HashEvalCheckBox)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.HashEncodeButton = uni_Widget.ICTFEButton(self)
        self.HashEncodeButton.setMinimumSize(QtCore.QSize(120, 45))
        self.HashEncodeButton.setMaximumSize(QtCore.QSize(120, 45))
        self.HashEncodeButton.setObjectName("HashEncodeButton")
        self.horizontalLayout.addWidget(self.HashEncodeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.HashTextBox = uni_Widget.ICTFETextBox(self)
        self.HashTextBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.HashTextBox.setObjectName("HashTextBox")
        self.verticalLayout.addWidget(self.HashTextBox)
        self.horizontalLayout_13.addLayout(self.verticalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 516, 731))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.HashTips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.HashTips.setObjectName("HashTips")
        self.horizontalLayout_2.addWidget(self.HashTips)
        self.HashValueBox = uni_Widget.ICTFELineBox(self.scrollAreaWidgetContents)
        self.HashValueBox.setObjectName("HashValueBox")
        self.HashValueBox.setMinimumHeight(45)
        self.horizontalLayout_2.addWidget(self.HashValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MD5Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.MD5Tips.setObjectName("MD5Tips")
        self.horizontalLayout_3.addWidget(self.MD5Tips)
        self.MD5ValueBox = uni_Widget.ICTFELineBox(self.scrollAreaWidgetContents)
        self.MD5ValueBox.setObjectName("MD5ValueBox")
        self.MD5ValueBox.setMinimumHeight(45)
        self.horizontalLayout_3.addWidget(self.MD5ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SHA1Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.SHA1Tips.setObjectName("SHA1Tips")
        self.horizontalLayout_4.addWidget(self.SHA1Tips)
        self.SHA1ValueBox = uni_Widget.ICTFELineBox(self.scrollAreaWidgetContents)
        self.SHA1ValueBox.setObjectName("SHA1ValueBox")
        self.SHA1ValueBox.setMinimumHeight(45)
        self.horizontalLayout_4.addWidget(self.SHA1ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SHA224Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.SHA224Tips.setObjectName("SHA224Tips")
        self.horizontalLayout_5.addWidget(self.SHA224Tips)
        self.SHA224ValueBox = uni_Widget.ICTFELineBox(
            self.scrollAreaWidgetContents)
        self.SHA224ValueBox.setObjectName("SHA224ValueBox")
        self.SHA224ValueBox.setMinimumHeight(45)
        self.horizontalLayout_5.addWidget(self.SHA224ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.SHA256Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.SHA256Tips.setObjectName("SHA256Tips")
        self.horizontalLayout_6.addWidget(self.SHA256Tips)
        self.SHA256ValueBox = uni_Widget.ICTFELineBox(
            self.scrollAreaWidgetContents)
        self.SHA256ValueBox.setObjectName("SHA256ValueBox")
        self.SHA256ValueBox.setMinimumHeight(45)
        self.horizontalLayout_6.addWidget(self.SHA256ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.SHA384Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.SHA384Tips.setObjectName("SHA384Tips")
        self.horizontalLayout_7.addWidget(self.SHA384Tips)
        self.SHA384ValueBox = uni_Widget.ICTFELineBox(
            self.scrollAreaWidgetContents)
        self.SHA384ValueBox.setObjectName("SHA384ValueBox")
        self.SHA384ValueBox.setMinimumHeight(45)
        self.horizontalLayout_7.addWidget(self.SHA384ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.SHA512Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.SHA512Tips.setObjectName("SHA512Tips")
        self.horizontalLayout_8.addWidget(self.SHA512Tips)
        self.SHA512ValueBox = uni_Widget.ICTFELineBox(
            self.scrollAreaWidgetContents)
        self.SHA512ValueBox.setObjectName("SHA512ValueBox")
        self.SHA512ValueBox.setMinimumHeight(45)
        self.horizontalLayout_8.addWidget(self.SHA512ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.SHA3224Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.SHA3224Tips.setObjectName("SHA3224Tips")
        self.horizontalLayout_9.addWidget(self.SHA3224Tips)
        self.SHA3224ValueBox = uni_Widget.ICTFELineBox(
            self.scrollAreaWidgetContents)
        self.SHA3224ValueBox.setObjectName("SHA3224ValueBox")
        self.SHA3224ValueBox.setMinimumHeight(45)
        self.horizontalLayout_9.addWidget(self.SHA3224ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.SHA3256Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.SHA3256Tips.setObjectName("SHA3256Tips")
        self.horizontalLayout_10.addWidget(self.SHA3256Tips)
        self.SHA3256ValueBox = uni_Widget.ICTFELineBox(
            self.scrollAreaWidgetContents)
        self.SHA3256ValueBox.setObjectName("SHA3256ValueBox")
        self.SHA3256ValueBox.setMinimumHeight(45)
        self.horizontalLayout_10.addWidget(self.SHA3256ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.SHA3384Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.SHA3384Tips.setObjectName("SHA3384Tips")
        self.horizontalLayout_11.addWidget(self.SHA3384Tips)
        self.SHA3384ValueBox = uni_Widget.ICTFELineBox(
            self.scrollAreaWidgetContents)
        self.SHA3384ValueBox.setObjectName("SHA3384ValueBox")
        self.SHA3384ValueBox.setMinimumHeight(45)
        self.horizontalLayout_11.addWidget(self.SHA3384ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.SHA3512Tips = uni_Widget.ICTFELabel(self.scrollAreaWidgetContents)
        self.SHA3512Tips.setTextFormat(QtCore.Qt.AutoText)
        self.SHA3512Tips.setObjectName("SHA3512Tips")
        self.horizontalLayout_12.addWidget(self.SHA3512Tips)
        self.SHA3512ValueBox = uni_Widget.ICTFELineBox(
            self.scrollAreaWidgetContents)
        self.SHA3512ValueBox.setObjectName("SHA3512ValueBox")
        self.SHA3512ValueBox.setMinimumHeight(45)
        self.horizontalLayout_12.addWidget(self.SHA3512ValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_13.addWidget(self.scrollArea)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.HashTextInputButton.setText(_translate("self", "打开"))
        self.HashEncodingTips.setText(_translate("self", "编码表:"))
        self.HashSaltTips.setText(_translate("self", "加盐:"))
        self.HashEvalCheckBox.setText(_translate("self", "Eval"))
        self.HashEncodeButton.setText(_translate("self", "计算"))
        self.HashTips.setText(_translate("self", "Hash:"))
        self.MD5Tips.setText(_translate("self", "MD5:"))
        self.SHA1Tips.setText(_translate("self", "SHA1:"))
        self.SHA224Tips.setText(_translate("self", "SHA224:"))
        self.SHA256Tips.setText(_translate("self", "SHA256:"))
        self.SHA384Tips.setText(_translate("self", "SHA384:"))
        self.SHA512Tips.setText(_translate("self", "SHA512:"))
        self.SHA3224Tips.setText(_translate("self", "SHA3-224:"))
        self.SHA3256Tips.setText(_translate("self", "SHA3-256:"))
        self.SHA3384Tips.setText(_translate("self", "SHA3-384:"))
        self.SHA3512Tips.setText(_translate("self", "SHA3-512:"))
