# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CryptoPanelUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1228, 718)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CryptoMainSpliter = QtWidgets.QSplitter(Form)
        self.CryptoMainSpliter.setOrientation(QtCore.Qt.Horizontal)
        self.CryptoMainSpliter.setObjectName("CryptoMainSpliter")
        self.ToolsArea = QtWidgets.QScrollArea(self.CryptoMainSpliter)
        self.ToolsArea.setWidgetResizable(True)
        self.ToolsArea.setObjectName("ToolsArea")
        self.ToolsAreaPanel = QtWidgets.QWidget()
        self.ToolsAreaPanel.setGeometry(QtCore.QRect(0, 0, 386, 698))
        self.ToolsAreaPanel.setObjectName("ToolsAreaPanel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ToolsAreaPanel)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ToolsSearchBox = QtWidgets.QLineEdit(self.ToolsAreaPanel)
        self.ToolsSearchBox.setObjectName("ToolsSearchBox")
        self.verticalLayout_5.addWidget(self.ToolsSearchBox)
        self.ToolsList = QtWidgets.QListWidget(self.ToolsAreaPanel)
        self.ToolsList.setObjectName("ToolsList")
        self.verticalLayout_5.addWidget(self.ToolsList)
        self.ToolsArea.setWidget(self.ToolsAreaPanel)
        self.widget = QtWidgets.QWidget(self.CryptoMainSpliter)
        self.widget.setObjectName("widget")
        self.NodeEditorLayout = QtWidgets.QVBoxLayout(self.widget)
        self.NodeEditorLayout.setContentsMargins(0, 0, 0, 0)
        self.NodeEditorLayout.setObjectName("NodeEditorLayout")
        self.ToolBarWidget = QtWidgets.QWidget(self.widget)
        self.ToolBarWidget.setMinimumSize(QtCore.QSize(0, 54))
        self.ToolBarWidget.setMaximumSize(QtCore.QSize(16777215, 54))
        self.ToolBarWidget.setObjectName("ToolBarWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ToolBarWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StartButton = QtWidgets.QPushButton(self.ToolBarWidget)
        self.StartButton.setMinimumSize(QtCore.QSize(0, 54))
        self.StartButton.setObjectName("StartButton")
        self.horizontalLayout.addWidget(self.StartButton)
        self.MainProcess = QtWidgets.QProgressBar(self.ToolBarWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainProcess.sizePolicy().hasHeightForWidth())
        self.MainProcess.setSizePolicy(sizePolicy)
        self.MainProcess.setMinimumSize(QtCore.QSize(0, 54))
        self.MainProcess.setProperty("value", 24)
        self.MainProcess.setObjectName("MainProcess")
        self.horizontalLayout.addWidget(self.MainProcess)
        self.NodeEditorLayout.addWidget(self.ToolBarWidget)
        self.CryptoToolNodeEditor = QtWidgets.QWidget(self.widget)
        self.CryptoToolNodeEditor.setObjectName("CryptoToolNodeEditor")
        self.NodeEditorLayout.addWidget(self.CryptoToolNodeEditor)
        self.FileAndOptionsLayout = QtWidgets.QSplitter(self.CryptoMainSpliter)
        self.FileAndOptionsLayout.setOrientation(QtCore.Qt.Vertical)
        self.FileAndOptionsLayout.setObjectName("FileAndOptionsLayout")
        self.OptionsArea = QtWidgets.QScrollArea(self.FileAndOptionsLayout)
        self.OptionsArea.setWidgetResizable(True)
        self.OptionsArea.setObjectName("OptionsArea")
        self.OptionsAreaPanel = QtWidgets.QWidget()
        self.OptionsAreaPanel.setGeometry(QtCore.QRect(0, 0, 386, 348))
        self.OptionsAreaPanel.setObjectName("OptionsAreaPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.OptionsAreaPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.OptionsTips = QtWidgets.QLabel(self.OptionsAreaPanel)
        self.OptionsTips.setObjectName("OptionsTips")
        self.verticalLayout.addWidget(self.OptionsTips)
        self.OptionsBox = QtWidgets.QListView(self.OptionsAreaPanel)
        self.OptionsBox.setObjectName("OptionsBox")
        self.verticalLayout.addWidget(self.OptionsBox)
        self.OptionsArea.setWidget(self.OptionsAreaPanel)
        self.FileTempStackArea = QtWidgets.QScrollArea(self.FileAndOptionsLayout)
        self.FileTempStackArea.setWidgetResizable(True)
        self.FileTempStackArea.setObjectName("FileTempStackArea")
        self.FileTempStackAreaPanel = QtWidgets.QWidget()
        self.FileTempStackAreaPanel.setGeometry(QtCore.QRect(0, 0, 386, 347))
        self.FileTempStackAreaPanel.setObjectName("FileTempStackAreaPanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FileTempStackAreaPanel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FileTempStackTips = QtWidgets.QLabel(self.FileTempStackAreaPanel)
        self.FileTempStackTips.setObjectName("FileTempStackTips")
        self.verticalLayout_2.addWidget(self.FileTempStackTips)
        self.FileTempStack = QtWidgets.QListView(self.FileTempStackAreaPanel)
        self.FileTempStack.setObjectName("FileTempStack")
        self.verticalLayout_2.addWidget(self.FileTempStack)
        self.FileTempStackArea.setWidget(self.FileTempStackAreaPanel)
        self.horizontalLayout_2.addWidget(self.CryptoMainSpliter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.StartButton.setText(_translate("Form", "PushButton"))
        self.OptionsTips.setText(_translate("Form", "节点选项"))
        self.FileTempStackTips.setText(_translate("Form", "暂存池"))
