from PyQt5 import QtCore, QtWidgets, Qt, QtGui
from CryptoPanel.ui_CryptoPanel import ui_CryptoPanel


class CryptoPanel(ui_CryptoPanel):
    def __init__(self):
        super(CryptoPanel, self).__init__()

        self.BaseButton.clicked.connect(self.ChangeCryptoBase)
        self.QuoteButton.clicked.connect(self.ChangeCryptoQuote)
        self.UrlButton.clicked.connect(self.ChangeCryptoUrl)
        self.HexButton.clicked.connect(self.ChangeCryptoHex)
        self.HTMLButton.clicked.connect(self.ChangeCryptoHTML)
        self.EscapeButton.clicked.connect(self.ChangeCryptoEscape)
        self.TapButton.clicked.connect(self.ChangeCryptoTap)
        self.MorseButton.clicked.connect(self.ChangeCryptoMorse)
        self.HashButton.clicked.connect(self.ChangeCryptoHash)
        self.CaesarButton.clicked.connect(self.ChangeCryptoCaesar)
        self.RailFenceButton.clicked.connect(self.ChangeCryptoRailFence)
        self.ROTButton.clicked.connect(self.ChangeCryptoROT)
        self.StrokesButton.clicked.connect(self.ChangeCryptoStrokes)
        self.RSAButton.clicked.connect(self.ChangeCryptoRSA)

    def ChangeButtonColor(self, button):
        self.BaseButton.setStyleSheet("QPushButton{"
                                      "background-color:rgba(40, 40, 40, 100%);"
                                      "color: white;"
                                      "border-radius: 0px;"
                                      "border: 0px groove gray;"
                                      "border-style: outset;"
                                      "}"
                                      "QPushButton:hover{"
                                      "background-color: rgba(60, 60, 60, 100%);"
                                      "color: white;"
                                      "}"
                                      "QPushButton:pressed{"
                                      "background-color: rgb(100, 100, 100);"
                                      "border-style: inset; "
                                      "}")
        self.QuoteButton.setStyleSheet("QPushButton{"
                                       "background-color:rgba(40, 40, 40, 100%);"
                                       "color: white;"
                                       "border-radius: 0px;"
                                       "border: 0px groove gray;"
                                       "border-style: outset;"
                                       "}"
                                       "QPushButton:hover{"
                                       "background-color: rgba(60, 60, 60, 100%);"
                                       "color: white;"
                                       "}"
                                       "QPushButton:pressed{"
                                       "background-color: rgb(100, 100, 100);"
                                       "border-style: inset; "
                                       "}")
        self.UrlButton.setStyleSheet("QPushButton{"
                                     "background-color:rgba(40, 40, 40, 100%);"
                                     "color: white;"
                                     "border-radius: 0px;"
                                     "border: 0px groove gray;"
                                     "border-style: outset;"
                                     "}"
                                     "QPushButton:hover{"
                                     "background-color: rgba(60, 60, 60, 100%);"
                                     "color: white;"
                                     "}"
                                     "QPushButton:pressed{"
                                     "background-color: rgb(100, 100, 100);"
                                     "border-style: inset; "
                                     "}")
        self.HexButton.setStyleSheet("QPushButton{"
                                     "background-color:rgba(40, 40, 40, 100%);"
                                     "color: white;"
                                     "border-radius: 0px;"
                                     "border: 0px groove gray;"
                                     "border-style: outset;"
                                     "}"
                                     "QPushButton:hover{"
                                     "background-color: rgba(60, 60, 60, 100%);"
                                     "color: white;"
                                     "}"
                                     "QPushButton:pressed{"
                                     "background-color: rgb(100, 100, 100);"
                                     "border-style: inset; "
                                     "}")
        self.HTMLButton.setStyleSheet("QPushButton{"
                                      "background-color:rgba(40, 40, 40, 100%);"
                                      "color: white;"
                                      "border-radius: 0px;"
                                      "border: 0px groove gray;"
                                      "border-style: outset;"
                                      "}"
                                      "QPushButton:hover{"
                                      "background-color: rgba(60, 60, 60, 100%);"
                                      "color: white;"
                                      "}"
                                      "QPushButton:pressed{"
                                      "background-color: rgb(100, 100, 100);"
                                      "border-style: inset; "
                                      "}")
        self.EscapeButton.setStyleSheet("QPushButton{"
                                        "background-color:rgba(40, 40, 40, 100%);"
                                        "color: white;"
                                        "border-radius: 0px;"
                                        "border: 0px groove gray;"
                                        "border-style: outset;"
                                        "}"
                                        "QPushButton:hover{"
                                        "background-color: rgba(60, 60, 60, 100%);"
                                        "color: white;"
                                        "}"
                                        "QPushButton:pressed{"
                                        "background-color: rgb(100, 100, 100);"
                                        "border-style: inset; "
                                        "}")
        self.TapButton.setStyleSheet("QPushButton{"
                                     "background-color:rgba(40, 40, 40, 100%);"
                                     "color: white;"
                                     "border-radius: 0px;"
                                     "border: 0px groove gray;"
                                     "border-style: outset;"
                                     "}"
                                     "QPushButton:hover{"
                                     "background-color: rgba(60, 60, 60, 100%);"
                                     "color: white;"
                                     "}"
                                     "QPushButton:pressed{"
                                     "background-color: rgb(100, 100, 100);"
                                     "border-style: inset; "
                                     "}")
        self.MorseButton.setStyleSheet("QPushButton{"
                                       "background-color:rgba(40, 40, 40, 100%);"
                                       "color: white;"
                                       "border-radius: 0px;"
                                       "border: 0px groove gray;"
                                       "border-style: outset;"
                                       "}"
                                       "QPushButton:hover{"
                                       "background-color: rgba(60, 60, 60, 100%);"
                                       "color: white;"
                                       "}"
                                       "QPushButton:pressed{"
                                       "background-color: rgb(100, 100, 100);"
                                       "border-style: inset; "
                                       "}")
        self.HashButton.setStyleSheet("QPushButton{"
                                      "background-color:rgba(40, 40, 40, 100%);"
                                      "color: white;"
                                      "border-radius: 0px;"
                                      "border: 0px groove gray;"
                                      "border-style: outset;"
                                      "}"
                                      "QPushButton:hover{"
                                      "background-color: rgba(60, 60, 60, 100%);"
                                      "color: white;"
                                      "}"
                                      "QPushButton:pressed{"
                                      "background-color: rgb(100, 100, 100);"
                                      "border-style: inset; "
                                      "}")
        self.AESButton.setStyleSheet("QPushButton{"
                                     "background-color:rgba(40, 40, 40, 100%);"
                                     "color: white;"
                                     "border-radius: 0px;"
                                     "border: 0px groove gray;"
                                     "border-style: outset;"
                                     "}"
                                     "QPushButton:hover{"
                                     "background-color: rgba(60, 60, 60, 100%);"
                                     "color: white;"
                                     "}"
                                     "QPushButton:pressed{"
                                     "background-color: rgb(100, 100, 100);"
                                     "border-style: inset; "
                                     "}")
        self.DESButton.setStyleSheet("QPushButton{"
                                     "background-color:rgba(40, 40, 40, 100%);"
                                     "color: white;"
                                     "border-radius: 0px;"
                                     "border: 0px groove gray;"
                                     "border-style: outset;"
                                     "}"
                                     "QPushButton:hover{"
                                     "background-color: rgba(60, 60, 60, 100%);"
                                     "color: white;"
                                     "}"
                                     "QPushButton:pressed{"
                                     "background-color: rgb(100, 100, 100);"
                                     "border-style: inset; "
                                     "}")
        self.RC4Button.setStyleSheet("QPushButton{"
                                     "background-color:rgba(40, 40, 40, 100%);"
                                     "color: white;"
                                     "border-radius: 0px;"
                                     "border: 0px groove gray;"
                                     "border-style: outset;"
                                     "}"
                                     "QPushButton:hover{"
                                     "background-color: rgba(60, 60, 60, 100%);"
                                     "color: white;"
                                     "}"
                                     "QPushButton:pressed{"
                                     "background-color: rgb(100, 100, 100);"
                                     "border-style: inset; "
                                     "}")
        self.ASCIITranslateButton.setStyleSheet("QPushButton{"
                                                "background-color:rgba(40, 40, 40, 100%);"
                                                "color: white;"
                                                "border-radius: 0px;"
                                                "border: 0px groove gray;"
                                                "border-style: outset;"
                                                "}"
                                                "QPushButton:hover{"
                                                "background-color: rgba(60, 60, 60, 100%);"
                                                "color: white;"
                                                "}"
                                                "QPushButton:pressed{"
                                                "background-color: rgb(100, 100, 100);"
                                                "border-style: inset; "
                                                "}")
        self.RSAButton.setStyleSheet("QPushButton{"
                                     "background-color:rgba(40, 40, 40, 100%);"
                                     "color: white;"
                                     "border-radius: 0px;"
                                     "border: 0px groove gray;"
                                     "border-style: outset;"
                                     "}"
                                     "QPushButton:hover{"
                                     "background-color: rgba(60, 60, 60, 100%);"
                                     "color: white;"
                                     "}"
                                     "QPushButton:pressed{"
                                     "background-color: rgb(100, 100, 100);"
                                     "border-style: inset; "
                                     "}")
        self.CodeTranslateButton.setStyleSheet("QPushButton{"
                                               "background-color:rgba(40, 40, 40, 100%);"
                                               "color: white;"
                                               "border-radius: 0px;"
                                               "border: 0px groove gray;"
                                               "border-style: outset;"
                                               "}"
                                               "QPushButton:hover{"
                                               "background-color: rgba(60, 60, 60, 100%);"
                                               "color: white;"
                                               "}"
                                               "QPushButton:pressed{"
                                               "background-color: rgb(100, 100, 100);"
                                               "border-style: inset; "
                                               "}")
        self.ADFGVXButton.setStyleSheet("QPushButton{"
                                        "background-color:rgba(40, 40, 40, 100%);"
                                        "color: white;"
                                        "border-radius: 0px;"
                                        "border: 0px groove gray;"
                                        "border-style: outset;"
                                        "}"
                                        "QPushButton:hover{"
                                        "background-color: rgba(60, 60, 60, 100%);"
                                        "color: white;"
                                        "}"
                                        "QPushButton:pressed{"
                                        "background-color: rgb(100, 100, 100);"
                                        "border-style: inset; "
                                        "}")
        self.AffineButton.setStyleSheet("QPushButton{"
                                        "background-color:rgba(40, 40, 40, 100%);"
                                        "color: white;"
                                        "border-radius: 0px;"
                                        "border: 0px groove gray;"
                                        "border-style: outset;"
                                        "}"
                                        "QPushButton:hover{"
                                        "background-color: rgba(60, 60, 60, 100%);"
                                        "color: white;"
                                        "}"
                                        "QPushButton:pressed{"
                                        "background-color: rgb(100, 100, 100);"
                                        "border-style: inset; "
                                        "}")
        self.AutoKeyButton.setStyleSheet("QPushButton{"
                                         "background-color:rgba(40, 40, 40, 100%);"
                                         "color: white;"
                                         "border-radius: 0px;"
                                         "border: 0px groove gray;"
                                         "border-style: outset;"
                                         "}"
                                         "QPushButton:hover{"
                                         "background-color: rgba(60, 60, 60, 100%);"
                                         "color: white;"
                                         "}"
                                         "QPushButton:pressed{"
                                         "background-color: rgb(100, 100, 100);"
                                         "border-style: inset; "
                                         "}")
        self.AtbashButton.setStyleSheet("QPushButton{"
                                        "background-color:rgba(40, 40, 40, 100%);"
                                        "color: white;"
                                        "border-radius: 0px;"
                                        "border: 0px groove gray;"
                                        "border-style: outset;"
                                        "}"
                                        "QPushButton:hover{"
                                        "background-color: rgba(60, 60, 60, 100%);"
                                        "color: white;"
                                        "}"
                                        "QPushButton:pressed{"
                                        "background-color: rgb(100, 100, 100);"
                                        "border-style: inset; "
                                        "}")
        self.BeaufortButton.setStyleSheet("QPushButton{"
                                          "background-color:rgba(40, 40, 40, 100%);"
                                          "color: white;"
                                          "border-radius: 0px;"
                                          "border: 0px groove gray;"
                                          "border-style: outset;"
                                          "}"
                                          "QPushButton:hover{"
                                          "background-color: rgba(60, 60, 60, 100%);"
                                          "color: white;"
                                          "}"
                                          "QPushButton:pressed{"
                                          "background-color: rgb(100, 100, 100);"
                                          "border-style: inset; "
                                          "}")
        self.BifidButton.setStyleSheet("QPushButton{"
                                       "background-color:rgba(40, 40, 40, 100%);"
                                       "color: white;"
                                       "border-radius: 0px;"
                                       "border: 0px groove gray;"
                                       "border-style: outset;"
                                       "}"
                                       "QPushButton:hover{"
                                       "background-color: rgba(60, 60, 60, 100%);"
                                       "color: white;"
                                       "}"
                                       "QPushButton:pressed{"
                                       "background-color: rgb(100, 100, 100);"
                                       "border-style: inset; "
                                       "}")
        self.CaesarButton.setStyleSheet("QPushButton{"
                                        "background-color:rgba(40, 40, 40, 100%);"
                                        "color: white;"
                                        "border-radius: 0px;"
                                        "border: 0px groove gray;"
                                        "border-style: outset;"
                                        "}"
                                        "QPushButton:hover{"
                                        "background-color: rgba(60, 60, 60, 100%);"
                                        "color: white;"
                                        "}"
                                        "QPushButton:pressed{"
                                        "background-color: rgb(100, 100, 100);"
                                        "border-style: inset; "
                                        "}")
        self.CTButton.setStyleSheet("QPushButton{"
                                    "background-color:rgba(40, 40, 40, 100%);"
                                    "color: white;"
                                    "border-radius: 0px;"
                                    "border: 0px groove gray;"
                                    "border-style: outset;"
                                    "}"
                                    "QPushButton:hover{"
                                    "background-color: rgba(60, 60, 60, 100%);"
                                    "color: white;"
                                    "}"
                                    "QPushButton:pressed{"
                                    "background-color: rgb(100, 100, 100);"
                                    "border-style: inset; "
                                    "}")
        self.EnigmaButton.setStyleSheet("QPushButton{"
                                        "background-color:rgba(40, 40, 40, 100%);"
                                        "color: white;"
                                        "border-radius: 0px;"
                                        "border: 0px groove gray;"
                                        "border-style: outset;"
                                        "}"
                                        "QPushButton:hover{"
                                        "background-color: rgba(60, 60, 60, 100%);"
                                        "color: white;"
                                        "}"
                                        "QPushButton:pressed{"
                                        "background-color: rgb(100, 100, 100);"
                                        "border-style: inset; "
                                        "}")
        self.FourSquareButton.setStyleSheet("QPushButton{"
                                            "background-color:rgba(40, 40, 40, 100%);"
                                            "color: white;"
                                            "border-radius: 0px;"
                                            "border: 0px groove gray;"
                                            "border-style: outset;"
                                            "}"
                                            "QPushButton:hover{"
                                            "background-color: rgba(60, 60, 60, 100%);"
                                            "color: white;"
                                            "}"
                                            "QPushButton:pressed{"
                                            "background-color: rgb(100, 100, 100);"
                                            "border-style: inset; "
                                            "}")
        self.GronsFeldButton.setStyleSheet("QPushButton{"
                                           "background-color:rgba(40, 40, 40, 100%);"
                                           "color: white;"
                                           "border-radius: 0px;"
                                           "border: 0px groove gray;"
                                           "border-style: outset;"
                                           "}"
                                           "QPushButton:hover{"
                                           "background-color: rgba(60, 60, 60, 100%);"
                                           "color: white;"
                                           "}"
                                           "QPushButton:pressed{"
                                           "background-color: rgb(100, 100, 100);"
                                           "border-style: inset; "
                                           "}")
        self.M209Button.setStyleSheet("QPushButton{"
                                      "background-color:rgba(40, 40, 40, 100%);"
                                      "color: white;"
                                      "border-radius: 0px;"
                                      "border: 0px groove gray;"
                                      "border-style: outset;"
                                      "}"
                                      "QPushButton:hover{"
                                      "background-color: rgba(60, 60, 60, 100%);"
                                      "color: white;"
                                      "}"
                                      "QPushButton:pressed{"
                                      "background-color: rgb(100, 100, 100);"
                                      "border-style: inset; "
                                      "}")
        self.PlayFairButton.setStyleSheet("QPushButton{"
                                          "background-color:rgba(40, 40, 40, 100%);"
                                          "color: white;"
                                          "border-radius: 0px;"
                                          "border: 0px groove gray;"
                                          "border-style: outset;"
                                          "}"
                                          "QPushButton:hover{"
                                          "background-color: rgba(60, 60, 60, 100%);"
                                          "color: white;"
                                          "}"
                                          "QPushButton:pressed{"
                                          "background-color: rgb(100, 100, 100);"
                                          "border-style: inset; "
                                          "}")
        self.PolybiusButton.setStyleSheet("QPushButton{"
                                          "background-color:rgba(40, 40, 40, 100%);"
                                          "color: white;"
                                          "border-radius: 0px;"
                                          "border: 0px groove gray;"
                                          "border-style: outset;"
                                          "}"
                                          "QPushButton:hover{"
                                          "background-color: rgba(60, 60, 60, 100%);"
                                          "color: white;"
                                          "}"
                                          "QPushButton:pressed{"
                                          "background-color: rgb(100, 100, 100);"
                                          "border-style: inset; "
                                          "}")
        self.PortaButton.setStyleSheet("QPushButton{"
                                       "background-color:rgba(40, 40, 40, 100%);"
                                       "color: white;"
                                       "border-radius: 0px;"
                                       "border: 0px groove gray;"
                                       "border-style: outset;"
                                       "}"
                                       "QPushButton:hover{"
                                       "background-color: rgba(60, 60, 60, 100%);"
                                       "color: white;"
                                       "}"
                                       "QPushButton:pressed{"
                                       "background-color: rgb(100, 100, 100);"
                                       "border-style: inset; "
                                       "}")
        self.RailFenceButton.setStyleSheet("QPushButton{"
                                           "background-color:rgba(40, 40, 40, 100%);"
                                           "color: white;"
                                           "border-radius: 0px;"
                                           "border: 0px groove gray;"
                                           "border-style: outset;"
                                           "}"
                                           "QPushButton:hover{"
                                           "background-color: rgba(60, 60, 60, 100%);"
                                           "color: white;"
                                           "}"
                                           "QPushButton:pressed{"
                                           "background-color: rgb(100, 100, 100);"
                                           "border-style: inset; "
                                           "}")
        self.ROTButton.setStyleSheet("QPushButton{"
                                     "background-color:rgba(40, 40, 40, 100%);"
                                     "color: white;"
                                     "border-radius: 0px;"
                                     "border: 0px groove gray;"
                                     "border-style: outset;"
                                     "}"
                                     "QPushButton:hover{"
                                     "background-color: rgba(60, 60, 60, 100%);"
                                     "color: white;"
                                     "}"
                                     "QPushButton:pressed{"
                                     "background-color: rgb(100, 100, 100);"
                                     "border-style: inset; "
                                     "}")
        self.SubstitutionButton.setStyleSheet("QPushButton{"
                                              "background-color:rgba(40, 40, 40, 100%);"
                                              "color: white;"
                                              "border-radius: 0px;"
                                              "border: 0px groove gray;"
                                              "border-style: outset;"
                                              "}"
                                              "QPushButton:hover{"
                                              "background-color: rgba(60, 60, 60, 100%);"
                                              "color: white;"
                                              "}"
                                              "QPushButton:pressed{"
                                              "background-color: rgb(100, 100, 100);"
                                              "border-style: inset; "
                                              "}")
        self.VigenereButton.setStyleSheet("QPushButton{"
                                          "background-color:rgba(40, 40, 40, 100%);"
                                          "color: white;"
                                          "border-radius: 0px;"
                                          "border: 0px groove gray;"
                                          "border-style: outset;"
                                          "}"
                                          "QPushButton:hover{"
                                          "background-color: rgba(60, 60, 60, 100%);"
                                          "color: white;"
                                          "}"
                                          "QPushButton:pressed{"
                                          "background-color: rgb(100, 100, 100);"
                                          "border-style: inset; "
                                          "}")
        self.PigenButton.setStyleSheet("QPushButton{"
                                       "background-color:rgba(40, 40, 40, 100%);"
                                       "color: white;"
                                       "border-radius: 0px;"
                                       "border: 0px groove gray;"
                                       "border-style: outset;"
                                       "}"
                                       "QPushButton:hover{"
                                       "background-color: rgba(60, 60, 60, 100%);"
                                       "color: white;"
                                       "}"
                                       "QPushButton:pressed{"
                                       "background-color: rgb(100, 100, 100);"
                                       "border-style: inset; "
                                       "}")
        self.BaconButton.setStyleSheet("QPushButton{"
                                       "background-color:rgba(40, 40, 40, 100%);"
                                       "color: white;"
                                       "border-radius: 0px;"
                                       "border: 0px groove gray;"
                                       "border-style: outset;"
                                       "}"
                                       "QPushButton:hover{"
                                       "background-color: rgba(60, 60, 60, 100%);"
                                       "color: white;"
                                       "}"
                                       "QPushButton:pressed{"
                                       "background-color: rgb(100, 100, 100);"
                                       "border-style: inset; "
                                       "}")
        self.RunningKeyButton.setStyleSheet("QPushButton{"
                                            "background-color:rgba(40, 40, 40, 100%);"
                                            "color: white;"
                                            "border-radius: 0px;"
                                            "border: 0px groove gray;"
                                            "border-style: outset;"
                                            "}"
                                            "QPushButton:hover{"
                                            "background-color: rgba(60, 60, 60, 100%);"
                                            "color: white;"
                                            "}"
                                            "QPushButton:pressed{"
                                            "background-color: rgb(100, 100, 100);"
                                            "border-style: inset; "
                                            "}")
        self.HillButton.setStyleSheet("QPushButton{"
                                      "background-color:rgba(40, 40, 40, 100%);"
                                      "color: white;"
                                      "border-radius: 0px;"
                                      "border: 0px groove gray;"
                                      "border-style: outset;"
                                      "}"
                                      "QPushButton:hover{"
                                      "background-color: rgba(60, 60, 60, 100%);"
                                      "color: white;"
                                      "}"
                                      "QPushButton:pressed{"
                                      "background-color: rgb(100, 100, 100);"
                                      "border-style: inset; "
                                      "}")
        self.A1z26Button.setStyleSheet("QPushButton{"
                                       "background-color:rgba(40, 40, 40, 100%);"
                                       "color: white;"
                                       "border-radius: 0px;"
                                       "border: 0px groove gray;"
                                       "border-style: outset;"
                                       "}"
                                       "QPushButton:hover{"
                                       "background-color: rgba(60, 60, 60, 100%);"
                                       "color: white;"
                                       "}"
                                       "QPushButton:pressed{"
                                       "background-color: rgb(100, 100, 100);"
                                       "border-style: inset; "
                                       "}")
        self.BeaufortButton.setStyleSheet("QPushButton{"
                                          "background-color:rgba(40, 40, 40, 100%);"
                                          "color: white;"
                                          "border-radius: 0px;"
                                          "border: 0px groove gray;"
                                          "border-style: outset;"
                                          "}"
                                          "QPushButton:hover{"
                                          "background-color: rgba(60, 60, 60, 100%);"
                                          "color: white;"
                                          "}"
                                          "QPushButton:pressed{"
                                          "background-color: rgb(100, 100, 100);"
                                          "border-style: inset; "
                                          "}")
        self.OtherCipherButton.setStyleSheet("QPushButton{"
                                             "background-color:rgba(40, 40, 40, 100%);"
                                             "color: white;"
                                             "border-radius: 0px;"
                                             "border: 0px groove gray;"
                                             "border-style: outset;"
                                             "}"
                                             "QPushButton:hover{"
                                             "background-color: rgba(60, 60, 60, 100%);"
                                             "color: white;"
                                             "}"
                                             "QPushButton:pressed{"
                                             "background-color: rgb(100, 100, 100);"
                                             "border-style: inset; "
                                             "}")
        self.JSFuckButton.setStyleSheet("QPushButton{"
                                        "background-color:rgba(40, 40, 40, 100%);"
                                        "color: white;"
                                        "border-radius: 0px;"
                                        "border: 0px groove gray;"
                                        "border-style: outset;"
                                        "}"
                                        "QPushButton:hover{"
                                        "background-color: rgba(60, 60, 60, 100%);"
                                        "color: white;"
                                        "}"
                                        "QPushButton:pressed{"
                                        "background-color: rgb(100, 100, 100);"
                                        "border-style: inset; "
                                        "}")
        self.BrainFuckButton.setStyleSheet("QPushButton{"
                                           "background-color:rgba(40, 40, 40, 100%);"
                                           "color: white;"
                                           "border-radius: 0px;"
                                           "border: 0px groove gray;"
                                           "border-style: outset;"
                                           "}"
                                           "QPushButton:hover{"
                                           "background-color: rgba(60, 60, 60, 100%);"
                                           "color: white;"
                                           "}"
                                           "QPushButton:pressed{"
                                           "background-color: rgb(100, 100, 100);"
                                           "border-style: inset; "
                                           "}")
        self.OokButton.setStyleSheet("QPushButton{"
                                     "background-color:rgba(40, 40, 40, 100%);"
                                     "color: white;"
                                     "border-radius: 0px;"
                                     "border: 0px groove gray;"
                                     "border-style: outset;"
                                     "}"
                                     "QPushButton:hover{"
                                     "background-color: rgba(60, 60, 60, 100%);"
                                     "color: white;"
                                     "}"
                                     "QPushButton:pressed{"
                                     "background-color: rgb(100, 100, 100);"
                                     "border-style: inset; "
                                     "}")
        self.StrokesButton.setStyleSheet("QPushButton{"
                                         "background-color:rgba(40, 40, 40, 100%);"
                                         "color: white;"
                                         "border-radius: 0px;"
                                         "border: 0px groove gray;"
                                         "border-style: outset;"
                                         "}"
                                         "QPushButton:hover{"
                                         "background-color: rgba(60, 60, 60, 100%);"
                                         "color: white;"
                                         "}"
                                         "QPushButton:pressed{"
                                         "background-color: rgb(100, 100, 100);"
                                         "border-style: inset; "
                                         "}")
        button.setStyleSheet("QPushButton{"
                             "background-color:rgba(40, 140, 255, 100%);"
                             "color: white;"
                             "border-radius: 0px;"
                             "border: 0px groove gray;"
                             "border-style: outset;"
                             "}"
                             "QPushButton:hover{"
                             "background-color: rgba(60, 60, 255, 100%);"
                             "color: white;"
                             "}"
                             "QPushButton:pressed{"
                             "background-color: rgb(100, 100, 255);"
                             "border-style: inset; "
                             "}")

    def ChangeCryptoStrokes(self):
        self.CryptoStack.setCurrentWidget(self.StrokesPanel)
        self.ChangeButtonColor(self.StrokesButton)

    def ChangeCryptoROT(self):
        self.CryptoStack.setCurrentWidget(self.ROTPanel)
        self.ChangeButtonColor(self.ROTButton)

    def ChangeCryptoRailFence(self):
        self.CryptoStack.setCurrentWidget(self.RailFencePanel)
        self.ChangeButtonColor(self.RailFenceButton)

    def ChangeCryptoCaesar(self):
        self.CryptoStack.setCurrentWidget(self.CaesarPanel)
        self.ChangeButtonColor(self.CaesarButton)
        self.CaesarPanel.CaesarLimitBox.setText('26')
        self.CaesarPanel.CaesarStepBox.setText('0')
        self.CaesarPanel.CaesarDispBox.setText('0')

    # RSA工具

    def ChangeCryptoRSA(self):
        self.CryptoStack.setCurrentWidget(self.RSAPanel)
        self.ChangeButtonColor(self.RSAButton)
        # self.RSAPanel.ChangeRSA()

    def ChangeCryptoHash(self):
        self.CryptoStack.setCurrentWidget(self.HashPanel)
        self.ChangeButtonColor(self.HashButton)
        self.HashPanel.HashEncodingBox.setText('UTF-8')

    def ChangeCryptoMorse(self):
        self.CryptoStack.setCurrentWidget(self.MorsePanel)
        self.ChangeButtonColor(self.MorseButton)
        self.MorsePanel.MorseSpiltBox.setText('/')

    def ChangeCryptoTap(self):
        self.CryptoStack.setCurrentWidget(self.TapPanel)
        self.ChangeButtonColor(self.TapButton)

    def ChangeCryptoEscape(self):
        self.CryptoStack.setCurrentWidget(self.EscapePanel)
        self.ChangeButtonColor(self.EscapeButton)

    def ChangeCryptoHTML(self):
        self.CryptoStack.setCurrentWidget(self.HTMLPanel)
        self.ChangeButtonColor(self.HTMLButton)

    def ChangeCryptoHex(self):
        self.CryptoStack.setCurrentWidget(self.HexPanel)
        self.ChangeButtonColor(self.HexButton)
        self.HexPanel.HexSplitBox.setText('')

    def ChangeCryptoUrl(self):
        self.CryptoStack.setCurrentWidget(self.UrlPanel)
        self.ChangeButtonColor(self.UrlButton)
        self.UrlPanel.UrlTableBox.setText('utf-8')

    def ChangeCryptoQuote(self):
        self.CryptoStack.setCurrentWidget(self.QuotePanel)
        self.ChangeButtonColor(self.QuoteButton)

    def ChangeCryptoBase(self):
        self.CryptoStack.setCurrentWidget(self.BasePanel)
        self.ChangeButtonColor(self.BaseButton)
        self.BasePanel.ChangeBase64()
