from PyQt5 import QtCore, QtWidgets
from ui_Widgets import uni_Widget


class ui_CaesarPanel(QtWidgets.QWidget):
    def __init__(self):
        super(ui_CaesarPanel, self).__init__()

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CaesarDispTips = uni_Widget.ICTFELabel(self)
        self.CaesarDispTips.setMinimumSize(QtCore.QSize(60, 45))
        self.CaesarDispTips.setMaximumSize(QtCore.QSize(60, 45))
        self.CaesarDispTips.setObjectName("CaesarDispTips")
        self.horizontalLayout.addWidget(self.CaesarDispTips)
        self.CaesarDispBox = uni_Widget.ICTFELineBox(self)
        self.CaesarDispBox.setMinimumSize(QtCore.QSize(60, 45))
        self.CaesarDispBox.setMaximumSize(QtCore.QSize(60, 45))
        self.CaesarDispBox.setObjectName("CaesarDispBox")
        self.horizontalLayout.addWidget(self.CaesarDispBox)
        self.CaesarStepTips = uni_Widget.ICTFELabel(self)
        self.CaesarStepTips.setMinimumSize(QtCore.QSize(60, 45))
        self.CaesarStepTips.setMaximumSize(QtCore.QSize(60, 45))
        self.CaesarStepTips.setObjectName("CaesarStepTips")
        self.horizontalLayout.addWidget(self.CaesarStepTips)
        self.CaesarStepBox = uni_Widget.ICTFELineBox(self)
        self.CaesarStepBox.setMinimumSize(QtCore.QSize(60, 45))
        self.CaesarStepBox.setMaximumSize(QtCore.QSize(60, 45))
        self.CaesarStepBox.setObjectName("CaesarStepBox")
        self.horizontalLayout.addWidget(self.CaesarStepBox)
        self.CaesarLimitTips = uni_Widget.ICTFELabel(self)
        self.CaesarLimitTips.setMinimumSize(QtCore.QSize(60, 45))
        self.CaesarLimitTips.setMaximumSize(QtCore.QSize(60, 45))
        self.CaesarLimitTips.setObjectName("CaesarLimitTips")
        self.horizontalLayout.addWidget(self.CaesarLimitTips)
        self.CaesarLimitBox = uni_Widget.ICTFELineBox(self)
        self.CaesarLimitBox.setMinimumSize(QtCore.QSize(60, 45))
        self.CaesarLimitBox.setMaximumSize(QtCore.QSize(60, 45))
        self.CaesarLimitBox.setObjectName("CaesarLimitBox")
        self.horizontalLayout.addWidget(self.CaesarLimitBox)
        self.CaesarDigitCheckBox = uni_Widget.ICTFECheckBox(self)
        self.CaesarDigitCheckBox.setMinimumSize(QtCore.QSize(100, 45))
        self.CaesarDigitCheckBox.setMaximumSize(QtCore.QSize(100, 45))
        self.CaesarDigitCheckBox.setObjectName("CaesarDigitCheckBox")
        self.horizontalLayout.addWidget(self.CaesarDigitCheckBox)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.CaesarEncryptButton = uni_Widget.ICTFEButton(self)
        self.CaesarEncryptButton.setMinimumSize(QtCore.QSize(120, 45))
        self.CaesarEncryptButton.setMaximumSize(QtCore.QSize(120, 45))
        self.CaesarEncryptButton.setObjectName("CaesarEncryptButton")
        self.horizontalLayout.addWidget(self.CaesarEncryptButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.CaesarTextBox = uni_Widget.ICTFETextBox(self)
        self.CaesarTextBox.setObjectName("CaesarTextBox")
        self.verticalLayout.addWidget(self.CaesarTextBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.CaesarDecryptButton = uni_Widget.ICTFEButton(self)
        self.CaesarDecryptButton.setMinimumSize(QtCore.QSize(120, 45))
        self.CaesarDecryptButton.setMaximumSize(QtCore.QSize(120, 45))
        self.CaesarDecryptButton.setObjectName("CaesarDecryptButton")
        self.horizontalLayout_2.addWidget(self.CaesarDecryptButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.CaesarCipherBox = uni_Widget.ICTFETextBox(self)
        self.CaesarCipherBox.setObjectName("CaesarCipherBox")
        self.verticalLayout_2.addWidget(self.CaesarCipherBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.CaesarDispTips.setText(_translate("self", "位移:"))
        self.CaesarStepTips.setText(_translate("self", "Step:"))
        self.CaesarLimitTips.setText(_translate("self", "Lim:"))
        self.CaesarDigitCheckBox.setText(_translate("self", "数字"))
        self.CaesarEncryptButton.setText(_translate("self", "加密"))
        self.CaesarDecryptButton.setText(_translate("self", "解密"))
        # end Caesar panel
